apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ein-secret-provider
  namespace: default
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "9c912d82-263b-417f-84e4-90bbc6d71335"
    tenantId: 693dd18b-8dba-406f-bad2-d195f40158e0
    keyvaultName: corpnet-formpal-keyvault
    objects: |
      array:
        - |
          objectName: SALESFORCE-CLIENT-ID
          objectType: secret
        - |
          objectName: SALESFORCE-CLIENT-SECRET
          objectType: secret
        - |
          objectName: SALESFORCE-ENDPOINT
          objectType: secret
        - |
          objectName: SALESFORCE-USERNAME
          objectType: secret
        - |
          objectName: SALESFORCE-PASSWORD
          objectType: secret
        - |
          objectName: SALESFORCE-TOKEN
          objectType: secret
        - |
          objectName: AZURE-STORAGE-ACCOUNT-NAME
          objectType: secret
        - |
          objectName: AZURE-ACCESS-KEY
          objectType: secret
        - |
          objectName: AZURE-CONTAINER-NAME
          objectType: secret
        - |
          objectName: TENANT-ID
          objectType: secret
        - |
          objectName: CLIENT-ID
          objectType: secret
        - |
          objectName: CLIENT-SECRET
          objectType: secret
        - |
          objectName: REDIRECT-URI
          objectType: secret
        - |
          objectName: PORT
          objectType: secret
        - |
          objectName: ALLOW-UNAUTHENTICATED-SALESFORCE
          objectType: secret
        - |
          objectName: API-KEY
          objectType: secret
  secretObjects:
    - secretName: ein-secrets
      type: Opaque
      data:
        - objectName: PORT
          key: PORT
        - objectName: API-KEY
          key: API_KEY
        - objectName: ALLOW-UNAUTHENTICATED-SALESFORCE
          key: ALLOW_UNAUTHENTICATED_SALESFORCE
        - objectName: SALESFORCE-ENDPOINT
          key: SALESFORCE_ENDPOINT
        - objectName: SALESFORCE-CLIENT-ID
          key: SALESFORCE_CLIENT_ID
        - objectName: SALESFORCE-CLIENT-SECRET
          key: SALESFORCE_CLIENT_SECRET
        - objectName: SALESFORCE-USERNAME
          key: SALESFORCE_USERNAME
        - objectName: SALESFORCE-PASSWORD
          key: SALESFORCE_PASSWORD
        - objectName: SALESFORCE-TOKEN
          key: SALESFORCE_TOKEN
        - objectName: AZURE-STORAGE-ACCOUNT-NAME
          key: AZURE_STORAGE_ACCOUNT_NAME
        - objectName: AZURE-ACCESS-KEY
          key: AZURE_ACCESS_KEY
        - objectName: AZURE-CONTAINER-NAME
          key: AZURE_CONTAINER_NAME
        - objectName: TENANT-ID
          key: TENANT_ID
        - objectName: CLIENT-ID
          key: CLIENT_ID
        - objectName: CLIENT-SECRET
          key: CLIENT_SECRET
        - objectName: REDIRECT-URI
          key: REDIRECT_URI
